/*

    This file is part of OpenMyEWB.

    OpenMyEWB is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenMyEWB is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenMyEWB.  If not, see <http://www.gnu.org/licenses/>.

    OpenMyEWB is Copyright 2005-2009 Nicolas Kruchten (nicolas@kruchten.com), Francis Kung, Engineers Without Borders Canada, Michael Trauttmansdorff, Jon Fishbein, David Kadish

*/

package ca.myewb.frame;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;

public class Countries {
	
	ArrayList<String> isoNames = new ArrayList<String>();
	Hashtable<String, String> countryNames = new Hashtable<String, String>();
	
	public Countries()
	{
		isoNames.add("AF");
		isoNames.add("AX");
		isoNames.add("AL");
		isoNames.add("DZ");
		isoNames.add("AS");
		isoNames.add("AD");
		isoNames.add("AO");
		isoNames.add("AI");
		isoNames.add("AQ");
		isoNames.add("AG");
		isoNames.add("AR");
		isoNames.add("AM");
		isoNames.add("AW");
		isoNames.add("AU");
		isoNames.add("AT");
		isoNames.add("AZ");
		isoNames.add("BS");
		isoNames.add("BH");
		isoNames.add("BD");
		isoNames.add("BB");
		isoNames.add("BY");
		isoNames.add("BE");
		isoNames.add("BZ");
		isoNames.add("BJ");
		isoNames.add("BM");
		isoNames.add("BT");
		isoNames.add("BO");
		isoNames.add("BA");
		isoNames.add("BW");
		isoNames.add("BV");
		isoNames.add("BR");
		isoNames.add("IO");
		isoNames.add("BN");
		isoNames.add("BG");
		isoNames.add("BF");
		isoNames.add("BI");
		isoNames.add("KH");
		isoNames.add("CM");
		isoNames.add("CV");
		isoNames.add("KY");
		isoNames.add("CF");
		isoNames.add("TD");
		isoNames.add("CL");
		isoNames.add("CN");
		isoNames.add("CX");
		isoNames.add("CC");
		isoNames.add("CO");
		isoNames.add("KM");
		isoNames.add("CG");
		isoNames.add("CD");
		isoNames.add("CK");
		isoNames.add("CR");
		isoNames.add("HR");
		isoNames.add("CU");
		isoNames.add("CY");
		isoNames.add("CZ");
		isoNames.add("CI");
		isoNames.add("DK");
		isoNames.add("DJ");
		isoNames.add("DM");
		isoNames.add("DO");
		isoNames.add("EC");
		isoNames.add("EG");
		isoNames.add("SV");
		isoNames.add("GQ");
		isoNames.add("ER");
		isoNames.add("EE");
		isoNames.add("ET");
		isoNames.add("FK");
		isoNames.add("FO");
		isoNames.add("FJ");
		isoNames.add("FI");
		isoNames.add("FR");
		isoNames.add("GF");
		isoNames.add("PF");
		isoNames.add("TF");
		isoNames.add("GA");
		isoNames.add("GM");
		isoNames.add("GE");
		isoNames.add("DE");
		isoNames.add("GH");
		isoNames.add("GI");
		isoNames.add("GR");
		isoNames.add("GL");
		isoNames.add("GD");
		isoNames.add("GP");
		isoNames.add("GU");
		isoNames.add("GT");
		isoNames.add("GG");
		isoNames.add("GN");
		isoNames.add("GW");
		isoNames.add("GY");
		isoNames.add("HT");
		isoNames.add("HM");
		isoNames.add("VA");
		isoNames.add("HN");
		isoNames.add("HK");
		isoNames.add("HU");
		isoNames.add("IS");
		isoNames.add("IN");
		isoNames.add("ID");
		isoNames.add("IR");
		isoNames.add("IQ");
		isoNames.add("IE");
		isoNames.add("IM");
		isoNames.add("IL");
		isoNames.add("IT");
		isoNames.add("JM");
		isoNames.add("JP");
		isoNames.add("JE");
		isoNames.add("JO");
		isoNames.add("KZ");
		isoNames.add("KE");
		isoNames.add("KI");
		isoNames.add("KP");
		isoNames.add("KR");
		isoNames.add("KW");
		isoNames.add("KG");
		isoNames.add("LA");
		isoNames.add("LV");
		isoNames.add("LB");
		isoNames.add("LS");
		isoNames.add("LR");
		isoNames.add("LY");
		isoNames.add("LI");
		isoNames.add("LT");
		isoNames.add("LU");
		isoNames.add("MO");
		isoNames.add("MK");
		isoNames.add("MG");
		isoNames.add("MW");
		isoNames.add("MY");
		isoNames.add("MV");
		isoNames.add("ML");
		isoNames.add("MT");
		isoNames.add("MH");
		isoNames.add("MQ");
		isoNames.add("MR");
		isoNames.add("MU");
		isoNames.add("YT");
		isoNames.add("MX");
		isoNames.add("FM");
		isoNames.add("MD");
		isoNames.add("MC");
		isoNames.add("MN");
		isoNames.add("ME");
		isoNames.add("MS");
		isoNames.add("MA");
		isoNames.add("MZ");
		isoNames.add("MM");
		isoNames.add("NA");
		isoNames.add("NR");
		isoNames.add("NP");
		isoNames.add("AN");
		isoNames.add("NL");
		isoNames.add("NC");
		isoNames.add("NZ");
		isoNames.add("NI");
		isoNames.add("NE");
		isoNames.add("NG");
		isoNames.add("NU");
		isoNames.add("NF");
		isoNames.add("MP");
		isoNames.add("NO");
		isoNames.add("OM");
		isoNames.add("PK");
		isoNames.add("PW");
		isoNames.add("PS");
		isoNames.add("PA");
		isoNames.add("PG");
		isoNames.add("PY");
		isoNames.add("PE");
		isoNames.add("PH");
		isoNames.add("PN");
		isoNames.add("PL");
		isoNames.add("PT");
		isoNames.add("PR");
		isoNames.add("QA");
		isoNames.add("RO");
		isoNames.add("RU");
		isoNames.add("RW");
		isoNames.add("RE");
		isoNames.add("SH");
		isoNames.add("KN");
		isoNames.add("LC");
		isoNames.add("PM");
		isoNames.add("VC");
		isoNames.add("WS");
		isoNames.add("SM");
		isoNames.add("ST");
		isoNames.add("SA");
		isoNames.add("SN");
		isoNames.add("RS");
		isoNames.add("SC");
		isoNames.add("SL");
		isoNames.add("SG");
		isoNames.add("SK");
		isoNames.add("SI");
		isoNames.add("SB");
		isoNames.add("SO");
		isoNames.add("ZA");
		isoNames.add("GS");
		isoNames.add("ES");
		isoNames.add("LK");
		isoNames.add("SD");
		isoNames.add("SR");
		isoNames.add("SJ");
		isoNames.add("SZ");
		isoNames.add("SE");
		isoNames.add("CH");
		isoNames.add("SY");
		isoNames.add("TW");
		isoNames.add("TJ");
		isoNames.add("TZ");
		isoNames.add("TH");
		isoNames.add("TL");
		isoNames.add("TG");
		isoNames.add("TK");
		isoNames.add("TO");
		isoNames.add("TT");
		isoNames.add("TN");
		isoNames.add("TR");
		isoNames.add("TM");
		isoNames.add("TC");
		isoNames.add("TV");
		isoNames.add("UG");
		isoNames.add("UA");
		isoNames.add("AE");
		isoNames.add("GB");
		isoNames.add("UM");
		isoNames.add("UY");
		isoNames.add("UZ");
		isoNames.add("VU");
		isoNames.add("VE");
		isoNames.add("VN");
		isoNames.add("VG");
		isoNames.add("VI");
		isoNames.add("WF");
		isoNames.add("EH");
		isoNames.add("YE");
		isoNames.add("ZM");
		isoNames.add("ZW");

		countryNames.put("AF","Afghanistan");
		countryNames.put("AX","Aland Islands");
		countryNames.put("AL","Albania");
		countryNames.put("DZ","Algeria");
		countryNames.put("AS","American Samoa");
		countryNames.put("AD","Andorra");
		countryNames.put("AO","Angola");
		countryNames.put("AI","Anguilla");
		countryNames.put("AQ","Antarctica");
		countryNames.put("AG","Antigua and Barbuda");
		countryNames.put("AR","Argentina");
		countryNames.put("AM","Armenia");
		countryNames.put("AW","Aruba");
		countryNames.put("AU","Australia");
		countryNames.put("AT","Austria");
		countryNames.put("AZ","Azerbaijan");
		countryNames.put("BS","Bahamas");
		countryNames.put("BH","Bahrain");
		countryNames.put("BD","Bangladesh");
		countryNames.put("BB","Barbados");
		countryNames.put("BY","Belarus");
		countryNames.put("BE","Belgium");
		countryNames.put("BZ","Belize");
		countryNames.put("BJ","Benin");
		countryNames.put("BM","Bermuda");
		countryNames.put("BT","Bhutan");
		countryNames.put("BO","Bolivia");
		countryNames.put("BA","Bosnia and Herzegovina");
		countryNames.put("BW","Botswana");
		countryNames.put("BV","Bouvet Island");
		countryNames.put("BR","Brazil");
		countryNames.put("IO","British Indian Ocean Territory");
		countryNames.put("BN","Brunei Darussalam");
		countryNames.put("BG","Bulgaria");
		countryNames.put("BF","Burkina Faso");
		countryNames.put("BI","Burundi");
		countryNames.put("KH","Cambodia");
		countryNames.put("CM","Cameroon");
		countryNames.put("CV","Cape Verde");
		countryNames.put("KY","Cayman Islands");
		countryNames.put("CF","Central African Republic");
		countryNames.put("TD","Chad");
		countryNames.put("CL","Chile");
		countryNames.put("CN","China");
		countryNames.put("CX","Christmas Island");
		countryNames.put("CC","Cocos (Keeling) Islands");
		countryNames.put("CO","Colombia");
		countryNames.put("KM","Comoros");
		countryNames.put("CG","Congo");
		countryNames.put("CD","Congo, the Democratic Republic of the");
		countryNames.put("CK","Cook Islands");
		countryNames.put("CR","Costa Rica");
		countryNames.put("HR","Croatia");
		countryNames.put("CU","Cuba");
		countryNames.put("CY","Cyprus");
		countryNames.put("CZ","Czech Republic");
		countryNames.put("CI","Cote d'Ivoire");
		countryNames.put("DK","Denmark");
		countryNames.put("DJ","Djibouti");
		countryNames.put("DM","Dominica");
		countryNames.put("DO","Dominican Republic");
		countryNames.put("EC","Ecuador");
		countryNames.put("EG","Egypt");
		countryNames.put("SV","El Salvador");
		countryNames.put("GQ","Equatorial Guinea");
		countryNames.put("ER","Eritrea");
		countryNames.put("EE","Estonia");
		countryNames.put("ET","Ethiopia");
		countryNames.put("FK","Falkland Islands (Malvinas)");
		countryNames.put("FO","Faroe Islands");
		countryNames.put("FJ","Fiji");
		countryNames.put("FI","Finland");
		countryNames.put("FR","France");
		countryNames.put("GF","French Guiana");
		countryNames.put("PF","French Polynesia");
		countryNames.put("TF","French Southern Territories");
		countryNames.put("GA","Gabon");
		countryNames.put("GM","Gambia");
		countryNames.put("GE","Georgia");
		countryNames.put("DE","Germany");
		countryNames.put("GH","Ghana");
		countryNames.put("GI","Gibraltar");
		countryNames.put("GR","Greece");
		countryNames.put("GL","Greenland");
		countryNames.put("GD","Grenada");
		countryNames.put("GP","Guadeloupe");
		countryNames.put("GU","Guam");
		countryNames.put("GT","Guatemala");
		countryNames.put("GG","Guernsey");
		countryNames.put("GN","Guinea");
		countryNames.put("GW","Guinea-Bissau");
		countryNames.put("GY","Guyana");
		countryNames.put("HT","Haiti");
		countryNames.put("HM","Heard Island and McDonald Islands");
		countryNames.put("VA","Holy See (Vatican City State)");
		countryNames.put("HN","Honduras");
		countryNames.put("HK","Hong Kong");
		countryNames.put("HU","Hungary");
		countryNames.put("IS","Iceland");
		countryNames.put("IN","India");
		countryNames.put("ID","Indonesia");
		countryNames.put("IR","Iran, Islamic Republic of");
		countryNames.put("IQ","Iraq");
		countryNames.put("IE","Ireland");
		countryNames.put("IM","Isle of Man");
		countryNames.put("IL","Israel");
		countryNames.put("IT","Italy");
		countryNames.put("JM","Jamaica");
		countryNames.put("JP","Japan");
		countryNames.put("JE","Jersey");
		countryNames.put("JO","Jordan");
		countryNames.put("KZ","Kazakhstan");
		countryNames.put("KE","Kenya");
		countryNames.put("KI","Kiribati");
		countryNames.put("KP","Korea, Democratic People's Republic of");
		countryNames.put("KR","Korea, Republic of");
		countryNames.put("KW","Kuwait");
		countryNames.put("KG","Kyrgyzstan");
		countryNames.put("LA","Lao People's Democratic Republic");
		countryNames.put("LV","Latvia");
		countryNames.put("LB","Lebanon");
		countryNames.put("LS","Lesotho");
		countryNames.put("LR","Liberia");
		countryNames.put("LY","Libyan Arab Jamahiriya");
		countryNames.put("LI","Liechtenstein");
		countryNames.put("LT","Lithuania");
		countryNames.put("LU","Luxembourg");
		countryNames.put("MO","Macao");
		countryNames.put("MK","Macedonia, the former Yugoslav Republic of");
		countryNames.put("MG","Madagascar");
		countryNames.put("MW","Malawi");
		countryNames.put("MY","Malaysia");
		countryNames.put("MV","Maldives");
		countryNames.put("ML","Mali");
		countryNames.put("MT","Malta");
		countryNames.put("MH","Marshall Islands");
		countryNames.put("MQ","Martinique");
		countryNames.put("MR","Mauritania");
		countryNames.put("MU","Mauritius");
		countryNames.put("YT","Mayotte");
		countryNames.put("MX","Mexico");
		countryNames.put("FM","Micronesia, Federated States of");
		countryNames.put("MD","Moldova, Republic of");
		countryNames.put("MC","Monaco");
		countryNames.put("MN","Mongolia");
		countryNames.put("ME","Montenegro");
		countryNames.put("MS","Montserrat");
		countryNames.put("MA","Morocco");
		countryNames.put("MZ","Mozambique");
		countryNames.put("MM","Myanmar");
		countryNames.put("NA","Namibia");
		countryNames.put("NR","Nauru");
		countryNames.put("NP","Nepal");
		countryNames.put("AN","Netherlands Antilles");
		countryNames.put("NL","Netherlands");
		countryNames.put("NC","New Caledonia");
		countryNames.put("NZ","New Zealand");
		countryNames.put("NI","Nicaragua");
		countryNames.put("NE","Niger");
		countryNames.put("NG","Nigeria");
		countryNames.put("NU","Niue");
		countryNames.put("NF","Norfolk Island");
		countryNames.put("MP","Northern Mariana Islands");
		countryNames.put("NO","Norway");
		countryNames.put("OM","Oman");
		countryNames.put("PK","Pakistan");
		countryNames.put("PW","Palau");
		countryNames.put("PS","Palestinian Territory, Occupied");
		countryNames.put("PA","Panama");
		countryNames.put("PG","Papua New Guinea");
		countryNames.put("PY","Paraguay");
		countryNames.put("PE","Peru");
		countryNames.put("PH","Philippines");
		countryNames.put("PN","Pitcairn");
		countryNames.put("PL","Poland");
		countryNames.put("PT","Portugal");
		countryNames.put("PR","Puerto Rico");
		countryNames.put("QA","Qatar");
		countryNames.put("RO","Romania");
		countryNames.put("RU","Russian Federation");
		countryNames.put("RW","Rwanda");
		countryNames.put("RE","Reunion");
		countryNames.put("SH","Saint Helena");
		countryNames.put("KN","Saint Kitts and Nevis");
		countryNames.put("LC","Saint Lucia");
		countryNames.put("PM","Saint Pierre and Miquelon");
		countryNames.put("VC","Saint Vincent and the Grenadines");
		countryNames.put("WS","Samoa");
		countryNames.put("SM","San Marino");
		countryNames.put("ST","Sao Tome and Principe");
		countryNames.put("SA","Saudi Arabia");
		countryNames.put("SN","Senegal");
		countryNames.put("RS","Serbia");
		countryNames.put("SC","Seychelles");
		countryNames.put("SL","Sierra Leone");
		countryNames.put("SG","Singapore");
		countryNames.put("SK","Slovakia");
		countryNames.put("SI","Slovenia");
		countryNames.put("SB","Solomon Islands");
		countryNames.put("SO","Somalia");
		countryNames.put("ZA","South Africa");
		countryNames.put("GS","South Georgia and the South Sandwich Islands");
		countryNames.put("ES","Spain");
		countryNames.put("LK","Sri Lanka");
		countryNames.put("SD","Sudan");
		countryNames.put("SR","Suriname");
		countryNames.put("SJ","Svalbard and Jan Mayen");
		countryNames.put("SZ","Swaziland");
		countryNames.put("SE","Sweden");
		countryNames.put("CH","Switzerland");
		countryNames.put("SY","Syrian Arab Republic");
		countryNames.put("TW","Taiwan, Province of China");
		countryNames.put("TJ","Tajikistan");
		countryNames.put("TZ","Tanzania, United Republic of");
		countryNames.put("TH","Thailand");
		countryNames.put("TL","Timor-Leste");
		countryNames.put("TG","Togo");
		countryNames.put("TK","Tokelau");
		countryNames.put("TO","Tonga");
		countryNames.put("TT","Trinidad and Tobago");
		countryNames.put("TN","Tunisia");
		countryNames.put("TR","Turkey");
		countryNames.put("TM","Turkmenistan");
		countryNames.put("TC","Turks and Caicos Islands");
		countryNames.put("TV","Tuvalu");
		countryNames.put("UG","Uganda");
		countryNames.put("UA","Ukraine");
		countryNames.put("AE","United Arab Emirates");
		countryNames.put("GB","United Kingdom");
		countryNames.put("UM","United States Minor Outlying Islands");
		countryNames.put("UY","Uruguay");
		countryNames.put("UZ","Uzbekistan");
		countryNames.put("VU","Vanuatu");
		countryNames.put("VE","Venezuela");
		countryNames.put("VN","Viet Nam");
		countryNames.put("VG","Virgin Islands, British");
		countryNames.put("VI","Virgin Islands, U.S.");
		countryNames.put("WF","Wallis and Futuna");
		countryNames.put("EH","Western Sahara");
		countryNames.put("YE","Yemen");
		countryNames.put("ZM","Zambia");
		countryNames.put("ZW","Zimbabwe");
	}

	public List<String> getCountryAbbreviations()
	{
		return isoNames;
	}
	
	public String getCountryName(String abbrev)
	{
		return countryNames.get(abbrev);
	}
}
